### ISSUE TITLE
How to construct weighted network from RNA-Seq data sets of mouse?

### ISSUE THREAD

**Issue by xflicsu** [omranian/inference-of-GRN-using-Fused-LASSO#1]
Hello,
    Fused-LASSO is a wonderful tool to predict regulatory network.
    I want to know how to build my weighted network from several 8 time-series RNA-Seq data sets?
    BTW, when I know the regulatory relationship from database of RegNetwork (http://www.regnetworkweb.org/) without weight, whether there is any method to set the weight to those network?
    Thanks for your attention.

**Comment by omranian** [comment]
Hi,

You can follow the steps explained in our manuscript.

To use the prior information, you can load initial beta with 1 at the places you know there is direct regulation between a TF and a gene. This should help you integrating your prior knowledge into the fused-lasso model.

Hope this is clear.
